# Generated by Django 5.1 on 2024-09-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarePath', '0004_admin_healthcareprovider_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprovider',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='customuser_ptr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provider_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='HealthcareProvider',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
