# Generated by Django 5.1 on 2024-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarePath', '0008_remove_message_user_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled'), ('Discharged', 'Discharged')], default='Active', max_length=20),
        ),
    ]
