# Generated by Django 5.1 on 2024-09-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarePath', '0010_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
