# Generated by Django 5.1 on 2024-09-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarePath', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
